// old_frontend/src/pages/users/[id]/components/UserByIdServicesBlock/components/UserByIdService/UserByIdServiceLayout.tsx
import {LayoutProps} from "@/types/LayoutProps";
import Link from "next/link";
import {UserService} from "@/types/UserService";
import PaperElement from "@/common-components/PaperElement";

type UserByIdServiceLayoutProps = LayoutProps & UserService;

const UserByIdServiceLayout = (props: UserByIdServiceLayoutProps) => {
    const {children, id} = props;

    return (
        <Link href={`/services/${id}`}>
            <PaperElement>
                {children}
            </PaperElement>
        </Link>
    )
}

export default UserByIdServiceLayout;

// frontend/src/pages/users/components/UserByIdServicesBlock/components/UserByIdService/UserByIdServiceLayout.svelte
<script lang="ts">
    import type {LayoutProps} from "@/types/LayoutProps.ts";
    import {Link} from "svelte-routing";
    import PaperElement from "@/common-components/PaperElement/PaperElement.svelte";
    import {getHoverClass} from "@/utils/utils.ts";

    type UserByIdServiceLayoutProps = LayoutProps & {
        id: number,
    }

    const {children, id}: UserByIdServiceLayoutProps = $props();
    const hoverClass = getHoverClass();
</script>

<Link to={`/services/${id}`}>
    <PaperElement styles={hoverClass}>
        {@render children()}
    </PaperElement>
</Link>
