// old_frontend/src/common-components/Sign/components/GoogleButton/GoogleButton.tsx
import {SignProps} from "@/types/SignProps";
import {handleGoogleSignInButtonClick} from "@/common-components/Sign/handlers";
import {useGoogleLogin} from "@react-oauth/google";

const GoogleButton = (props: SignProps) => {
    const {googleButtonText} = props;

    const onClick = useGoogleLogin({
        onSuccess: tokenResponse => handleGoogleSignInButtonClick(tokenResponse),
    });

    return (
        <button
            onClick={() => onClick()}
            type={"button"}
            className={"flex !h-11 font-semibold hover:bg-light-palette-action-hover dark:hover:bg-dark-palette-action-hover duration-200 ease-out active:scale-95 items-center justify-center border border-light-palette-divider dark:border-dark-palette-divider rounded-sm  gap-x-2 bg-light-palette-background-block dark:bg-dark-palette-background-block w-full"}
        >
            <span>{googleButtonText}</span>
            <img src={"/images/plus.png"} alt={"google"}/>
        </button>
    )
}

export default GoogleButton;

// frontend/src/common-components/Sign/components/GoogleButton/GoogleButton.svelte
<script lang="ts">
    import Icon from "@iconify/svelte";
    import {handleGoogleAuth, handleGoogleButtonClick} from "@/common-components/Sign/handlers.ts";
    import Spinner from "@/common-components/Spinner/Spinner.svelte";
    import type {SignProps} from "@/types/SignProps.ts";

    const {googleButtonText}: SignProps = $props();

    const clientId = import.meta.env.VITE_GOOGLE_CLIENT_ID;

    let loading = $state(false);
    const setLoading = (value: boolean) => loading = value;
</script>

{#if googleButtonText !== undefined}
    <button
            disabled={loading}
            onclick={() => handleGoogleButtonClick(setLoading, clientId)}
            type="button"
            class="{loading ? 'opacity-70' : 'active:scale-95 hover:bg-light-palette-action-hover dark:hover:bg-dark-palette-action-hover'} flex !h-12 bg-light-palette-background-block dark:bg-dark-palette-background-block font-semibold duration-200 ease-out items-center justify-center border border-light-palette-divider dark:border-dark-palette-divider rounded-md gap-x-2 w-full"
    >
        {#if loading}
            <Spinner size="size-8" color="border-l-white"/>
        {:else}
            <Icon icon="flat-color-icons:google" width="24" height="24"/>
            <span>{googleButtonText}</span>
        {/if}
    </button>
{/if}
