// frontend/src/pages/sign-in/components/SignInInputs/SignInInputs.svelte
<script lang="ts">
    import Input from "@/common-components/Input/Input.svelte";
    import {formStore} from "@/common-components/Sign/stores/form-store.ts";
    import type {FormStore} from "@/types/FormStore.ts";
    import KeepMeLoggedInBlock
        from "@/pages/sign-in/components/KeepMeSignedInBlock/KeepMeSignedInBlock.svelte";

    let formStoreData = $state<null | FormStore>(null);
    formStore.subscribe((value) => formStoreData = value);
</script>

{#if formStoreData && formStoreData.data && formStoreData.errors}
    <Input
            wasSubmitted={formStoreData.wasSubmitted}
            value={formStoreData.data.usernameOrEmail}
            error={formStoreData.errors.usernameOrEmail?.[0] || null}
            id="usernameOrEmail"
            type="text"
            label="Username or Email"
    />
    <Input
            wasSubmitted={formStoreData.wasSubmitted}
            value={formStoreData.data.password}
            error={formStoreData.errors.password?.[0] || null}
            id="password"
            type="password"
            label="Password"
    />
    <KeepMeLoggedInBlock/>
{/if}

// frontend/src/pages/sign-in/components/SignInInputs/SignInInputs.tsx
import MyInput from "@/common-components/MyInput/MyInput";
import {useFormContext} from "react-hook-form";
import {getErrorMessage} from "@/utils/input-utils";

const SignInInputs = () => {
    const {formState, register} = useFormContext();
    const {errors} = formState;

    return (
        <>
            <MyInput
                register={register}
                name={"email"}
                error={getErrorMessage(errors, 'email')}
                label={"Email"}/>
            <MyInput
                inputType={"password"}
                register={register}
                name={"password"}
                error={getErrorMessage(errors, 'password')}
                label={"Password"}
            />
        </>
    )
}

export default SignInInputs;
