// frontend/src/pages/users/components/UserAboutBlock/UserAboutBlock.svelte
<script lang="ts">
    import UserComponentLayout from "@/pages/users/components/UserComponentLayout.svelte";
    import Spoiler from "@/common-components/Spoiler/Spoiler.svelte";

    type UserAboutBlockProps = {
        about: string | null
    }

    const {about}: UserAboutBlockProps = $props();
</script>

{#if about !== null}
    <UserComponentLayout>
        <h2 class="text-xl font-bold">About</h2>
        <Spoiler>
            <p
                    class="text-base h-fit text-light-palette-text-secondary dark:text-dark-palette-text-secondary"
            >{@html about}</p>
        </Spoiler>
    </UserComponentLayout>
{/if}

// old_frontend/src/pages/users/[id]/components/UserAboutBlock/UserAboutBlock.tsx
import {UserByIdProps} from "@/types/UserByIdProps";
import {Spoiler} from "@mantine/core";
import UserComponentLayout from "@/pages/users/[id]/components/UserComponentLayout";

const UserAboutBlock = ({user}: UserByIdProps) => {
    const {about} = user;

    if(!about) return null;
    return (
        <UserComponentLayout>
            <h2 className="text-xl font-bold">About</h2>
            <Spoiler maxHeight={72} showLabel="Show more" hideLabel="Hide">
                <p
                    dangerouslySetInnerHTML={{__html: about}}
                    className="text-base text-light-palette-text-secondary dark:text-dark-palette-text-secondary"/>
            </Spoiler>
        </UserComponentLayout>
    );
}

export default UserAboutBlock;
