// frontend/src/pages/users/[id]/components/UserSkillsBlock/components/SkillBadge/SkillBadgeLayout.tsx
import {LayoutProps} from "@/types/LayoutProps";
import Link from "next/link";

type SkillBadgeLayoutProps = LayoutProps & {
    id: number
};

const SkillBadgeLayout = (props: SkillBadgeLayoutProps) => {
    const {children, id} = props;

    return (
        <Link
            href={"/search?skills=" + id}
            className={"rounded-xl border border-light-palette-divider dark:border-dark-palette-divider px-3 py-1 bg-light-palette-background-block dark:bg-dark-palette-background-block"}
        >
            {children}
        </Link>
    )
}

export default SkillBadgeLayout;

// frontend/src/pages/users/components/UserSkillsBlock/components/SkillBadge/SkillBadgeLayout.svelte
<script lang="ts">
    import type {LayoutProps} from "@/types/LayoutProps.ts";
    import {Link} from "svelte-routing";
    import {getHoverClass} from "@/utils/utils.ts";

    type SkillBadgeLayoutProps = {
        id: number,
    } & LayoutProps;

    let {id, children}: SkillBadgeLayoutProps = $props();
    const hoverClass = getHoverClass();
</script>


<Link
        to={"/search?skills=" + id}
        class={`rounded-xl border border-light-palette-divider dark:border-dark-palette-divider px-3 py-1 bg-light-palette-background-block dark:bg-dark-palette-background-block ${hoverClass}}`}
>
    {@render children()}
</Link>
