// frontend/src/pages/users/components/UserSkillsBlock/UserSkillsBlock.svelte
<script lang="ts">
    import type {Skill} from "@/types/Skill.ts";
    import UserComponentLayout from "@/pages/users/components/UserComponentLayout.svelte";
    import SkillBadge from "@/pages/users/components/UserSkillsBlock/components/SkillBadge/SkillBadge.svelte";

    type UserSkillsBlockProps = {
        skills: Skill[] | null
    }

    let {skills}: UserSkillsBlockProps = $props()
</script>

{#if skills !== null}
    <UserComponentLayout>
        <p class="text-xl font-bold">Skills</p>
        <div class="flex gap-x-2">
            {#each skills as skill }
                <SkillBadge skill={skill}/>
            {/each}
        </div>
    </UserComponentLayout>
{/if}

// frontend/src/pages/users/[id]/components/UserSkillsBlock/UserSkillsBlock.tsx
import {UserByIdProps} from "@/types/UserByIdProps";
import SkillBadge from "@/pages/users/[id]/components/UserSkillsBlock/components/SkillBadge/SkillBadge";
import UserComponentLayout from "@/pages/users/[id]/components/UserComponentLayout";

const UserSkillsBlock = (props: UserByIdProps) => {
    const {user} = props;
    const {skills} = user;

    if (!skills) return null;
    return (
        <UserComponentLayout>
            <p className={"text-xl font-bold"}>Skills</p>
            <div className={"flex gap-x-1"}>
                {skills.map((skill, index) => (
                    <SkillBadge skill={skill} key={index}/>
                ))}
            </div>
        </UserComponentLayout>
    )
}

export default UserSkillsBlock;
