// frontend/src/common-components/Sign/components/SignForm/SignForm.svelte
<script lang="ts">
    import type {SignProps} from "@/types/SignProps.ts";
    import Button from "@/common-components/Button/Button.svelte";
    import LeftSignSideOrText from "@/common-components/Sign/components/LeftSignSideOrText/LeftSignSideOrText.svelte";
    import SignFormLayout from "@/common-components/Sign/components/SignForm/SignFormLayout.svelte";
    import GoogleButton from "@/common-components/Sign/components/GoogleButton/GoogleButton.svelte";

    const signProps: SignProps = $props();
</script>

<SignFormLayout {...signProps}>
    {#if signProps.children}
        {@render signProps.children()}
    {/if}
    <Button
            styles="text-lg !h-14"
            type={"submit"}
    >{signProps.signButtonText}</Button>
    <LeftSignSideOrText/>
    <GoogleButton {...signProps}/>
</SignFormLayout>

// frontend/src/common-components/Sign/components/SignForm/SignForm.tsx
import SignFormLayout from "./SignFormLayout";
import MyButton from "@/common-components/MyButton/MyButton";
import LeftSignSideOrText from "@/common-components/Sign/components/LeftSignSideOrText/LeftSignSideOrText";
import SubFormText from "@/common-components/Sign/components/SubFormText/SubFormText";
import {SignProps} from "@/types/SignProps";

const SignForm = (props: SignProps) => {
    const {children, signButtonText} = props;

    return (
        <SignFormLayout {...props}>
            {children}
            <MyButton
                type={"submit"}
            >{signButtonText}</MyButton>
            <LeftSignSideOrText/>
            <SubFormText {...props}/>
        </SignFormLayout>
    )
}

export default SignForm;
