// frontend/src/pages/users/components/UserByIdServicesBlock/UserByIdServicesBlock.svelte
<script lang="ts">
    import UserComponentLayout from "@/pages/users/components/UserComponentLayout.svelte";
    import UserByIdService
        from "@/pages/users/components/UserByIdServicesBlock/components/UserByIdService/UserByIdService.svelte";
    import type {UserService} from "@/types/UserService.ts";

    type UserByIdServicesBlockProps = {
        services: UserService[] | null
    }

    const {services}: UserByIdServicesBlockProps = $props();
</script>

{#if services && services.length > 0}
    <UserComponentLayout>
        <h2 class="text-xl font-bold">Services</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {#each services as service}
                <UserByIdService service={service}/>
            {/each}
        </div>

    </UserComponentLayout>
{/if}

// frontend/src/pages/users/[id]/components/UserByIdServicesBlock/UserByIdServicesBlock.tsx
import UserComponentLayout from "@/pages/users/[id]/components/UserComponentLayout";
import { UserByIdProps } from "@/types/UserByIdProps";
import UserByIdService from "@/pages/users/[id]/components/UserByIdServicesBlock/components/UserByIdService/UserByIdService";

const UserByIdServicesBlock = ({ user }: UserByIdProps) => {
    const { services } = user;

    if (!services || services.length === 0) return null;

    return (
        <UserComponentLayout>
            <h2 className="text-xl font-bold">Services</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                {services.map((service, index) => (
                    <UserByIdService key={index} service={service} />
                ))}
            </div>
        </UserComponentLayout>
    );
}

export default UserByIdServicesBlock;
