// frontend/src/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewUser/UserByIdReviewUser.tsx
import UserByIdReviewUserLayout from "./UserByIdReviewUserLayout";
import {Avatar} from "@mantine/core";
import {getFile} from "@/utils/utils";
import {User} from "@/types/User";
import Link from "next/link";

type UserByIdReviewUserProps = User;

const UserByIdReviewUser = (props: UserByIdReviewUserProps) => {
    const {avatar, firstName, surname, id} = props;
    const link = `/users/${id}`;

    return (
        <UserByIdReviewUserLayout>
            <Link href={link}>
                <Avatar src={avatar && getFile(avatar)} size={48}/>
            </Link>
            <Link href={link}>
                <p className={"hover:underline ease-out duration-200"}>{firstName} {surname}</p>
            </Link>
        </UserByIdReviewUserLayout>
    )
}

export default UserByIdReviewUser;

// frontend/src/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewUser/UserByIdReviewUser.svelte
<script lang="ts">
  import type { User } from '@/types/User.ts'
  import UserByIdReviewUserLayout from '@/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewUser/UserByIdReviewUserLayout.svelte'
  import { Link } from 'svelte-routing'
  import Avatar from '@/common-components/Avatar/Avatar.svelte'

  type UserByIdReviewProps = User & {
    user_id?: number
  }

  const { avatar, username, id, user_id }: UserByIdReviewProps = $props()
</script>

<UserByIdReviewUserLayout>
  <Link to={`/users/${id === undefined ? user_id : id}`}>
    <Avatar src={avatar} alt="img" size={'extra small'} />
  </Link>
  <Link to={`/users/${id === undefined ? user_id : id}`}>
    <p class="hover:underline ease-out duration-200">{username}</p>
  </Link>
</UserByIdReviewUserLayout>
