// frontend/src/common-components/Footer/FooterLayout.svelte
<script>
    import PageLayout from "@/common-components/PageLayout.svelte";
</script>

<footer
        class={"border-t bg-light-palette-background-block dark:bg-dark-palette-background-block border-light-palette-divider dark:border-dark-palette-divider py-4"}
>
    <PageLayout>
        <div class={"flex md:flex-row flex-col gap-y-4 justify-between items-center text-light-palette-text-secondary dark:text-dark-palette-text-secondary"}>
            <slot/>
        </div>
    </PageLayout>
</footer>

// old_frontend/src/common-components/Footer/FooterLayout.tsx
import {LayoutProps} from "@/types/LayoutProps";
import PageLayout from "@/common-components/PageLayout";

const FooterLayout = (props: LayoutProps) => {
    const {children} = props;

    return (
        <footer
            className={"border bg-light-palette-background-block dark:bg-dark-palette-background-block border-light-palette-divider dark:border-dark-palette-divider py-4"}>
            <PageLayout>
                <div className={"flex md:flex-row flex-col gap-y-4 justify-between items-center text-light-palette-text-secondary dark:text-dark-palette-text-secondary"}>
                    {children}
                </div>
            </PageLayout>
        </footer>
    )
}

export default FooterLayout;
