// frontend/src/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/UserByIdReviewLayout.svelte
<script lang="ts">
    import type {LayoutProps} from "@/types/LayoutProps.ts";
    import PaperElement from "@/common-components/PaperElement/PaperElement.svelte";

    const {children}: LayoutProps = $props();
</script>

<PaperElement styles="flex flex-col gap-4">
    {@render children()}
</PaperElement>

// frontend/src/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/UserByIdReviewLayout.tsx
import {LayoutProps} from "@/types/LayoutProps";
import PaperElement from "@/common-components/PaperElement";

const UserByIdReviewLayout = (props: LayoutProps) => {
    const {children} = props;

    return (
        <PaperElement styles={"flex flex-col gap-4"}>
            {children}
        </PaperElement>
    )
}

export default UserByIdReviewLayout;
