// frontend/src/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/UserByIdReview.svelte
<script lang="ts">
  import type { Review } from '@/types/Review.ts'
  import UserByIdReviewLayout from '@/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/UserByIdReviewLayout.svelte'
  import UserByIdReviewUser from '@/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewUser/UserByIdReviewUser.svelte'
  import DividerElement from '@/common-components/DividerElement/DividerElement.svelte'
  import UserByIdReviewRatingBar from '@/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewRatingBar/UserByIdReviewRatingBar.svelte'
  import UserByIdReviewBottomContent from '@/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewBottomContent/UserByIdReviewBottomContent.svelte'
  import UserByIdReviewContent from '@/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewContent/UserByIdReviewContent.svelte'

  type UserByIdReviewProps = {
    review: Review
    showServices?: boolean
  }

  const { review, showServices }: UserByIdReviewProps = $props()
</script>

<UserByIdReviewLayout>
  <UserByIdReviewUser  {...review.customer} />
  <DividerElement />
  <UserByIdReviewRatingBar {...review} />
  <UserByIdReviewContent {...review} />
  <UserByIdReviewBottomContent {review} {showServices} />
</UserByIdReviewLayout>

// frontend/src/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/UserByIdReview.tsx
import UserByIdReviewLayout from "./UserByIdReviewLayout";
import {Review} from "@/types/Review";
import DividerElement from "@/common-components/DividerElement";
import {Avatar, Image, Rating} from "@mantine/core";
import BulletElement from "@/common-components/BulletElement";
import {getFile, getPackageDuration, getTimeAgo} from "@/utils/utils";
import Link from "next/link";
import UserByIdReviewUser
    from "@/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewUser/UserByIdReviewUser";
import UserByIdReviewRatingBar
    from "@/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewRatingBar/UserByIdReviewRatingBar";
import UserByIdReviewBottomContent
    from "@/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewBottomContent/UserByIdReviewBottomContent";

type UserByIdReviewProps = {
    review: Review,
    showServices?: boolean
}

const UserByIdReview = (props: UserByIdReviewProps) => {
    const {review} = props;
    const {customer} = review;

    return (
        <UserByIdReviewLayout>
            <UserByIdReviewUser {...customer}/>
            <DividerElement/>
            <UserByIdReviewRatingBar {...review}/>
            <UserByIdReviewBottomContent {...props}/>
        </UserByIdReviewLayout>
    )
}

export default UserByIdReview;
