// frontend/src/common-components/NotFound/NotFoundLayout.svelte
<script lang="ts">
    import type {LayoutProps} from "@/types/LayoutProps.ts";

    const {children} : LayoutProps = $props();
</script>

<div class="min-h-app w-full flex flex-col font-semibold text-light-palette-text-primary dark:text-dark-palette-text-primary select-none justify-center items-center">
    {@render children()}
</div>

// frontend/src/common-components/NotFound/NotFoundLayout.tsx
import {LayoutProps} from "@/types/LayoutProps";
import {motion} from "framer-motion";
import animation from "@/utils/animation.json";

const NotFoundLayout = (props: LayoutProps) => {
    const {children} = props;

    return (
        <motion.div
            {...animation}
            className={"min-h-app flex flex-col font-semibold text-light-palette-text-primary dark:text-dark-palette-text-primary select-none justify-center items-center"}
        >
            {children}
        </motion.div>
    )
}

export default NotFoundLayout;
