// frontend/src/common-components/PaperElement/PaperElement.svelte
<script lang="ts">
    import type {LayoutProps} from "@/types/LayoutProps.ts";

    type PaperElementProps = LayoutProps & {
        styles?: string,
    }

    const {children, styles}: PaperElementProps = $props();
</script>

<div
        class={`${styles} p-6 rounded-lg border border-light-palette-divider dark:border-dark-palette-divider`}
>
    {@render children()}
</div>

// frontend/src/common-components/PaperElement.tsx
import {LayoutProps} from "@/types/LayoutProps";

type PaperElementProps = LayoutProps & {
    styles?: string,
}

const PaperElement = (props: PaperElementProps) => {
    const {children, styles} = props;

    return (
        <div
            className={`${styles} py-4 px-6 rounded-lg border border-light-palette-divider dark:border-dark-palette-divider`}
        >
            {children}
        </div>
    )
}

export default PaperElement;
