// frontend/src/pages/services/components/ServicePackagesBlock/ServicePackagesBlock.svelte
<script lang="ts">
    import ServicePackagesBlockLayout
        from "@/pages/services/components/ServicePackagesBlock/ServicePackagesBlockLayout.svelte";
    import PackageTabList from "@/pages/services/components/PackageTabList/PackageTabList.svelte";
    import SelectedPackage from "@/pages/services/components/SelectedPackage/SelectedPackage.svelte";
    import type {Package} from "@/types/Package.ts";

    type ServicePackagesBlockProps = {
        packages: Package[]
    }

    const {packages}: ServicePackagesBlockProps = $props();
    const tabs = ['Basic', 'Standard', 'Premium'];
    let selectedTab = $state<number>(0);
    const setSelectedTab = (value: number) => selectedTab = value;
</script>

<ServicePackagesBlockLayout>
    <PackageTabList
            setSelectedTab={setSelectedTab}
            selectedTab={selectedTab}
            packages={packages}
            tabs={tabs}
    />
    <SelectedPackage {...packages[selectedTab]}/>
</ServicePackagesBlockLayout>

// frontend/src/pages/services/[id]/components/ServicePackagesBlock/ServicePackagesBlock.tsx
import ServicePackagesBlockLayout from "./ServicePackagesBlockLayout";
import {Package} from "@/types/Package";
import PackageTabList from "@/pages/services/[id]/components/PackageTabList/PackageTabList";
import {useState} from "react";
import SelectedPackage from "@/pages/services/[id]/components/SelectedPackage/SelectedPackage";

type ServicePackagesBlockProps = {
    packages: Package[]
}

const ServicePackagesBlock = (props: ServicePackagesBlockProps) => {
    const {packages} = props;
    const tabs = ['Basic', 'Standard', 'Premium'];
    const [selectedTab, setSelectedTab] = useState(0);

    return (
        <ServicePackagesBlockLayout>
            <PackageTabList
                setSelectedTab={setSelectedTab}
                selectedTab={selectedTab}
                packages={packages}
                tabs={tabs}
            />
            <SelectedPackage {...packages[selectedTab]}/>
        </ServicePackagesBlockLayout>
    )
}

export default ServicePackagesBlock;
