// frontend/src/pages/services/components/SelectedPackage/SelectedPackage.svelte
<script lang="ts">
    import type {Package} from "@/types/Package.ts";
    import SelectedPackageLayout from "@/pages/services/components/SelectedPackage/SelectedPackageLayout.svelte";
    import MyButton from "@/common-components/Button/Button.svelte";

    const {title, price, description, deliveryDays}: Package = $props();
    const primaryTextStyle = "text-light-palette-text-primary dark:text-dark-palette-text-primary";
</script>

<SelectedPackageLayout>
    <h2 class="${primaryTextStyle} text-xl font-semibold mb-4">{title}</h2>
    <p class="mb-4 text-sm">{description}</p>
    <div class="flex justify-between text-lg items-center ${primaryTextStyle}">
    <span>
        {deliveryDays} {deliveryDays > 1 ? "Days Delivery" : "Day Delivery"}
    </span>
        <p class="font-bold">{price}$</p>
    </div>
    <MyButton
            styles={"!mt-8 !w-full"}>
        Order Now
    </MyButton>
</SelectedPackageLayout>

// frontend/src/pages/services/[id]/components/SelectedPackage/SelectedPackage.tsx
import SelectedPackageLayout from "./SelectedPackageLayout";
import {Package} from "@/types/Package";
import {Button, NumberFormatter} from "@mantine/core";

type SelectedPackageProps = Package;

const SelectedPackage = (props: SelectedPackageProps) => {
    const {title, price, description, deliveryDays} = props;
    const primaryTextStyle = "text-light-palette-text-primary dark:text-dark-palette-text-primary";

    return (
        <SelectedPackageLayout>
            <h2 className={`${primaryTextStyle} text-xl font-semibold mb-4`}>{title}</h2>
            <p className="mb-4 text-sm">{description}</p>
            <div className={`flex justify-between text-lg items-center ${primaryTextStyle}`}>
                <span>
                    {deliveryDays} {deliveryDays > 1 ? "Days Delivery" : "Day Delivery"}
                </span>
                <NumberFormatter
                    className={"font-bold"}
                    prefix="$"
                    value={price}
                />
            </div>
            <Button className="mt-8 !w-full !bg-cyan-500 hover:!bg-cyan-400 transition-colors duration-200">
                Order Now
            </Button>
        </SelectedPackageLayout>
    );
};

export default SelectedPackage;
