// frontend/src/pages/services/[id]/components/ServiceAboutBlock/ServiceAboutBlock.tsx
import ServiceAboutBlockLayout from "./ServiceAboutBlockLayout";
import {Service} from "@/types/Service";

type ServiceAboutBlockProps = Service;

const ServiceAboutBlock = (props: ServiceAboutBlockProps) => {
    const {description} = props;

    return (
        <ServiceAboutBlockLayout>
            <h3 className={"text-xl font-bold text-light-palette-text-primary dark:text-dark-palette-text-primary"}>About</h3>
            <p
                className={"text-light-palette-text-secondary dark:text-dark-palette-text-secondary"}
            >{description}</p>
        </ServiceAboutBlockLayout>
    )
}

export default ServiceAboutBlock;

// frontend/src/pages/services/components/ServiceAboutBlock/ServiceAboutBlock.svelte
<script lang="ts">
    import ServiceAboutBlockLayout from "@/pages/services/components/ServiceAboutBlock/ServiceAboutBlockLayout.svelte";
    import type {Service} from "@/types/Service.ts";

    const {description}: Service = $props();
</script>

<ServiceAboutBlockLayout>
    <h3 class="text-xl font-bold text-light-palette-text-primary dark:text-dark-palette-text-primary">About</h3>
    <p
            class="text-light-palette-text-secondary dark:text-dark-palette-text-secondary"
    >{description}</p>
</ServiceAboutBlockLayout>
