// old_frontend/src/pages/services/[id]/components/ServiceContent/ServiceContent.tsx
import ServiceContentLayout from "./ServiceContentLayout";
import ServiceTopLeftSideContent
    from "@/pages/services/[id]/components/ServiceTopLeftSideContent/ServiceTopLeftSideContent";
import ServiceBottomLeftSideContent
    from "@/pages/services/[id]/components/ServiceBottomLeftSideContent/ServiceBottomLeftSideContent";
import ServicePackagesBlock from "@/pages/services/[id]/components/ServicePackagesBlock/ServicePackagesBlock";
import {Service} from "@/types/Service";

type ServiceTypeProps = Service;

const ServiceContent = (props: ServiceTypeProps) => {
    const {packages} = props;

    return (
        <ServiceContentLayout>
            <ServiceTopLeftSideContent {...props}/>
            <ServiceBottomLeftSideContent {...props}/>
            <ServicePackagesBlock packages={packages}/>
        </ServiceContentLayout>
    )
}

export default ServiceContent;

// frontend/src/pages/services/components/ServiceContent/ServiceContent.svelte
<script lang="ts">
    import ServiceContentLayout from "@/pages/services/components/ServiceContent/ServiceContentLayout.svelte";
    import ServiceBottomLeftSideContent
        from "@/pages/services/components/ServiceBottomLeftSideContent/ServiceBottomLeftSideContent.svelte";
    import ServiceTopLeftSideContent
        from "@/pages/services/components/ServiceTopLeftSideContent/ServiceTopLeftSideContent.svelte";
    import ServicePackagesBlock from "@/pages/services/components/ServicePackagesBlock/ServicePackagesBlock.svelte";
    import type {Service} from "@/types/Service.ts";

    const serviceProps: Service = $props();
</script>

<ServiceContentLayout>
    <ServiceTopLeftSideContent {...serviceProps}/>
    <ServiceBottomLeftSideContent {...serviceProps}/>
    <ServicePackagesBlock {...serviceProps}/>
</ServiceContentLayout>
