// frontend/src/pages/users/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServiceImage.svelte
<script lang="ts">
    import type {UserService} from "@/types/UserService.ts";

    let {image, title}: UserService = $props();

    let imageSrc = $state<string | undefined>();

    $effect(() => {
        imageSrc = image ? image : '/images/no-image.jpg';
    })
</script>

{#if imageSrc}
    <img
            src={imageSrc}
            alt={title}
            class="object-cover aspect-video !rounded-md mb-3"
    />
{/if}

// frontend/src/pages/users/[id]/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServiceImage.tsx
import {getFile} from "@/utils/utils";
import {Image} from "@mantine/core";
import {UserService} from "@/types/UserService";

type UserByIdServiceImageProps = UserService;

const UserByIdServiceImage = (props: UserByIdServiceImageProps) => {
    const {image, title} = props;

    return (
        <Image
            className="object-cover aspect-video !rounded-md mb-3"
            src={getFile(image)}
            alt={title}
            height={200}
            width={200}
        />
    )
}

export default UserByIdServiceImage;
