// frontend/src/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewServiceImage/UserByIdReviewServiceImage.tsx
import UserByIdReviewServiceImageLayout from "./UserByIdReviewServiceImageLayout";
import {Image} from "@mantine/core";
import {getFile} from "@/utils/utils";

type UserByIdReviewServiceImageProps = {
    src: string,
}

const UserByIdReviewServiceImage = (props: UserByIdReviewServiceImageProps) => {
    const {src} = props;

    return (
        <UserByIdReviewServiceImageLayout>
            <Image
                className={"object-center aspect-video w-full object-cover h-9"}
                src={getFile(src)}
                alt={"service"}
                width={48}
                height={48}
            />
        </UserByIdReviewServiceImageLayout>
    )
}

export default UserByIdReviewServiceImage;

// frontend/src/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewServiceImage/UserByIdReviewServiceImage.svelte
<script lang="ts">
    import UserByIdReviewServiceImageLayout
        from "@/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewServiceImage/UserByIdReviewServiceImageLayout.svelte";

    type UserByIdReviewServiceImageProps = {
        src: string
    }

    let {src}: UserByIdReviewServiceImageProps = $props();
    if(!src) src = "/images/no-image.jpg";
</script>

<UserByIdReviewServiceImageLayout>
    <img
            width={48}
            height={48}
            src={src}
            alt="img"
            class="object-center aspect-video w-full object-cover h-9"
    />
</UserByIdReviewServiceImageLayout>
