// old_frontend/src/common-components/Sign/components/SubFormText/SubFormText.tsx
import SubFormTextLayout from "./SubFormTextLayout";
import Link from "next/link";
import {SignProps} from "@/types/SignProps";

const SubFormText = (props: SignProps) => {
    const {subFormText, signButtonLinkText, subFormLink} = props;

    return (
        <SubFormTextLayout>
            <span>{subFormText}</span>
            <Link
                className={"text-cyan-500 hover:underline ease-out duration-200"}
                href={subFormLink}
            >{signButtonLinkText}</Link>
        </SubFormTextLayout>
    )
}

export default SubFormText;

// frontend/src/common-components/Sign/components/SubFormText/SubFormText.svelte
<script lang="ts">
    import SubFormTextLayout from "@/common-components/Sign/components/SubFormText/SubFormTextLayout.svelte";
    import {Link} from "svelte-routing";

    type SubFormTextProps = {
        subFormText: string;
        signButtonLinkText: string;
        subFormLink: string;
    }

    const {subFormText, signButtonLinkText, subFormLink}: SubFormTextProps = $props();
</script>


<SubFormTextLayout>
    <span>{subFormText}</span>
    <Link
            class="text-cyan-500 hover:underline ease-out duration-200"
            to={subFormLink}
    >{signButtonLinkText}</Link>
</SubFormTextLayout>
