// frontend/src/common-components/Header/HeaderLayout.svelte
<script lang="ts">
    import PageLayout from "@/common-components/PageLayout.svelte";
    import type {LayoutProps} from "@/types/LayoutProps.ts";

    const {children} : LayoutProps = $props();
</script>

<header class={"py-4 bg-light-palette-background-block dark:bg-dark-palette-background-block border-b border-light-palette-divider dark:border-dark-palette-divider shadow-sm w-full"}>
    <PageLayout>
        <div class={"flex w-full items-center justify-between"}>
            {@render children()}
        </div>
    </PageLayout>
</header>

// frontend/src/common-components/Header/HeaderLayout.tsx
import {LayoutProps} from "@/types/LayoutProps";
import PageLayout from "@/common-components/PageLayout";

const HeaderLayout = (props: LayoutProps) => {
    const {children} = props;

    return (
        <header className={"py-4 bg-light-palette-background-block dark:bg-dark-palette-background-block border-b border-light-palette-divider dark:border-dark-palette-divider shadow-sm w-full"}>
            <PageLayout>
                <div className={"flex items-center justify-between"}>
                    {children}
                </div>
            </PageLayout>
        </header>
    )
}

export default HeaderLayout;
