// frontend/src/common-components/Header/Header.tsx
import HeaderLayout from "./HeaderLayout";
import ThemeSwitch from "@/common-components/ThemeSwitch/ThemeSwitch";
import AppLogo from "@/common-components/AppLogo";

const Header = () => {
    return (
        <HeaderLayout>
            <AppLogo/>
            <ThemeSwitch/>
        </HeaderLayout>
    )
}

export default Header;

// frontend/src/common-components/Header/Header.svelte
<script>
    import HeaderLayout from "@/common-components/Header/HeaderLayout.svelte";
    import AppLogo from "@/common-components/AppLogo/AppLogo.svelte";
    import ThemeSwitch from "@/common-components/ThemeSwitch/ThemeSwitch.svelte";
</script>

<HeaderLayout>
    <AppLogo/>
    <ThemeSwitch/>
</HeaderLayout>
