// frontend/src/pages/users/[id]/components/UserByIdReviewBlock/UserByIdReviewBlock.tsx
import UserComponentLayout from "@/pages/users/[id]/components/UserComponentLayout";
import UserByIdReview from "@/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/UserByIdReview";
import {Review} from "@/types/Review";
import NoReviewsMessage
    from "@/pages/users/[id]/components/UserByIdReviewBlock/components/NoReviewsMessage/NoReviewsMessage";

type UserByIdReviewProps = {
    reviews: Review[] | null,
    showServices?: boolean
}

const UserByIdReviewBlock = (props: UserByIdReviewProps) => {
    const {reviews} = props;

    if (!reviews) return null;
    return (
        <UserComponentLayout>
            <p className={"text-xl font-bold"}>Reviews</p>
            <div className={"flex flex-col gap-y-4"}>
                {reviews.length === 0
                    ? <NoReviewsMessage/>
                    : reviews.map((review, index) => (
                        <UserByIdReview
                            {...props}
                            key={index}
                            review={review}
                        />
                    ))
                }
            </div>
        </UserComponentLayout>
    )
}

export default UserByIdReviewBlock;

// frontend/src/pages/users/components/UserByIdReviewBlock/UserByIdReviewBlock.svelte
<script lang="ts">
    import type {Review} from "@/types/Review.ts";
    import UserComponentLayout from "@/pages/users/components/UserComponentLayout.svelte";
    import NoReviewsMessage
        from "@/pages/users/components/UserByIdReviewBlock/components/NoReviewsMessage/NoReviewsMessage.svelte";
    import UserByIdReview
        from "@/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/UserByIdReview.svelte";

    type UserByIdReviewProps = {
        reviews: Review[] | null,
        showServices?: boolean
    }

    const {reviews, showServices}: UserByIdReviewProps = $props();
</script>

<UserComponentLayout>
    <p class="text-xl font-bold">Reviews</p>
    <div class="flex flex-col gap-y-8">
        {#if !reviews || reviews.length === 0}
            <NoReviewsMessage/>
        {:else}
            {#each reviews as review}
                <UserByIdReview
                        review={review}
                        showServices={showServices}
                />
            {/each}
        {/if}
    </div>
</UserComponentLayout>
