// frontend/src/pages/users/components/UserByIdServicesBlock/components/UserByIdService/UserByIdService.svelte
<script lang="ts">
    import type {UserService} from "@/types/UserService.ts";
    import UserByIdServiceLayout
        from "@/pages/users/components/UserByIdServicesBlock/components/UserByIdService/UserByIdServiceLayout.svelte";
    import UserByIdServiceImage
        from "@/pages/users/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServiceImage.svelte";
    import UserByIdServiceTitle
        from "@/pages/users/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServiceTitle.svelte";
    import UserByIdServiceInfo
        from "@/pages/users/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServiceInfo/UserByIdServiceInfo.svelte";
    import UserByIdServicePrice
        from "@/pages/users/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServicePrice.svelte";

    type UserByIdServiceProps = {
        service: UserService,
    }

    const {service}: UserByIdServiceProps = $props();
</script>

<UserByIdServiceLayout {...service}>
    <UserByIdServiceImage {...service}/>
    <UserByIdServiceTitle {...service}/>
    <UserByIdServiceInfo {...service}/>
    <UserByIdServicePrice {...service}/>
</UserByIdServiceLayout>

// frontend/src/pages/users/[id]/components/UserByIdServicesBlock/components/UserByIdService/UserByIdService.tsx
import UserByIdServiceLayout from "./UserByIdServiceLayout";
import {UserService} from "@/types/UserService";
import UserByIdServiceImage from "@/pages/users/[id]/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServiceImage";
import UserByIdServiceTitle from "@/pages/users/[id]/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServiceTitle";
import UserByIdServiceInfo from "@/pages/users/[id]/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServiceInfo/UserByIdServiceInfo";
import UserByIdServicePrice from "@/pages/users/[id]/components/UserByIdServicesBlock/components/UserByIdService/components/UserByIdServicePrice";

type UserByIdServiceProps = {
    service: UserService,
}

const UserByIdService = (props: UserByIdServiceProps) => {
    const {service} = props;

    return (
        <UserByIdServiceLayout {...service}>
            <UserByIdServiceImage {...service}/>
            <UserByIdServiceTitle {...service}/>
            <UserByIdServiceInfo {...service}/>
            <UserByIdServicePrice {...service}/>
        </UserByIdServiceLayout>
    )
}

export default UserByIdService;
