// frontend/src/pages/services/components/ServiceBottomLeftSideContent/ServiceBottomLeftSideContent.svelte
<script lang="ts">
    import ServiceBottomLeftSideContentLayout
        from "@/pages/services/components/ServiceBottomLeftSideContent/ServiceBottomLeftSideContentLayout.svelte";
    import ServiceAboutBlock from "@/pages/services/components/ServiceAboutBlock/ServiceAboutBlock.svelte";
    import UserByIdReviewBlock from "@/pages/users/components/UserByIdReviewBlock/UserByIdReviewBlock.svelte";
    import type {Service} from "@/types/Service.ts";

    const serviceProps: Service = $props();
</script>

<ServiceBottomLeftSideContentLayout>
    <ServiceAboutBlock {...serviceProps}/>
    <UserByIdReviewBlock showServices={false} {...serviceProps}/>
</ServiceBottomLeftSideContentLayout>

// frontend/src/pages/services/[id]/components/ServiceBottomLeftSideContent/ServiceBottomLeftSideContent.tsx
import {Service} from "@/types/Service";
import ServiceBottomLeftSideContentLayout from "./ServiceBottomLeftSideContentLayout";
import ServiceAboutBlock from "@/pages/services/[id]/components/ServiceAboutBlock/ServiceAboutBlock";
import UserByIdReviewBlock from "@/pages/users/[id]/components/UserByIdReviewBlock/UserByIdReviewBlock";

type ServiceBottomLeftSideContentProps = Service;

const ServiceBottomLeftSideContent = (props: ServiceBottomLeftSideContentProps) => {
    const {reviews} = props;

    return (
        <ServiceBottomLeftSideContentLayout>
            <ServiceAboutBlock {...props}/>
            <UserByIdReviewBlock showServices={false} reviews={reviews}/>
        </ServiceBottomLeftSideContentLayout>
    )
}

export default ServiceBottomLeftSideContent;
