// frontend/src/pages/users/components/UserInfoBlock/components/UserInfoReviews/UserInfoReviewsLayout.svelte
<script lang="ts">
    import type {LayoutProps} from "@/types/LayoutProps.ts";

    type UserInfoReviewsLayoutProps = LayoutProps & {
        size?: "small" | "large",
    };

    const {children, size}: UserInfoReviewsLayoutProps = $props();
</script>


<div
        class={`flex items-center text-light-palette-text-secondary dark:text-dark-palette-text-secondary gap-x-2
        ${size === "small" ? "text-base" : "text-lg"}`}
>
    {@render children()}
</div>

// frontend/src/pages/users/[id]/components/UserInfoBlock/components/UserInfoReviews/UserInfoReviewsLayout.tsx
import {LayoutProps} from "@/types/LayoutProps";

type UserInfoReviewsLayoutProps = LayoutProps & {
    size?: "small" | "large",
};

const UserInfoReviewsLayout = (props: UserInfoReviewsLayoutProps) => {
    const {children, size} = props;

    return (
        <div
            className={`flex items-center text-light-palette-text-secondary dark:text-dark-palette-text-secondary gap-x-2 
            ${size === "small" ? "text-base" : "text-lg"}`}
        >
            {children}
        </div>
    )
}

export default UserInfoReviewsLayout;
