// old_frontend/src/pages/users/[id]/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewService/UserByIdReviewServiceLayout.tsx
import {LayoutProps} from "@/types/LayoutProps";
import Link from "next/link";
import {UserReview} from "@/types/UserReview";

type UserByIdReviewServiceLayoutPros = LayoutProps & UserReview;

const UserByIdReviewServiceLayout = (props: UserByIdReviewServiceLayoutPros) => {
    const {children, id} = props;

    return (
        <Link
            href={`/services/${id}`}
            className={"py-2 px-4 ring-1 ring-light-palette-divider shadow rounded-xl flex gap-4 items-center w-full md:w-fit"}
        >
            {children}
        </Link>
    )
}

export default UserByIdReviewServiceLayout;

// frontend/src/pages/users/components/UserByIdReviewBlock/components/UserByIdReview/components/UserByIdReviewService/UserByIdReviewServiceLayout.svelte
<script lang="ts">
    import type {LayoutProps} from "@/types/LayoutProps.ts";
    import {Link} from "svelte-routing";
    import {getHoverClass} from "@/utils/utils.ts";

    type UserByIdReviewServiceLayoutPros = LayoutProps & {
        id: number
    };

    const {children, id}: UserByIdReviewServiceLayoutPros = $props();
    const hoverClass = getHoverClass();
</script>

<Link to={`/services/${id}`}>
    <div class="{hoverClass} py-2 px-4 ring-1 ring-light-palette-divider dark:ring-dark-palette-divider shadow rounded-xl flex gap-4 items-center w-full md:w-fit">
        {@render children()}
    </div>
</Link>
